name: Publish Docker

on:
  push:
    tags:
    - 'docker-push-v*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: chrisjsewell/aiida-core
        dockerfile: builds/aiida-core/Dockerfile
        context: builds/aiida-core/
        username: chrisjsewell
        password: ${{ secrets.DOCKER_HUB }}