name: Publish Docker

on:
  push:
    tags:
    - 'docker-push-v*'

jobs:

  build-aiida-core:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        requirements: ["1.2.1", "1.2.1-atomic"]
      fail-fast: false

    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        REQUIREMENTS: ${{ matrix.requirements }}
      with:
        name: chrisjsewell/aiida-core
        dockerfile: builds/aiida-core/Dockerfile
        context: builds/aiida-core/
        username: chrisjsewell
        password: ${{ secrets.DOCKER_HUB }}
        buildargs: REQUIREMENTS
        tags: ${{ matrix.requirements }}
        cache: true

  build-qe:

    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        qe_version: ["qe-6.5"]
        qe_make: ["pw", "pwall"]
      fail-fast: false

    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        QE_GIT_TAG: ${{ matrix.qe_version }}
        QE_MAKE: ${{ matrix.qe_make }}
      with:
        name: chrisjsewell/quantum-espresso
        dockerfile: builds/quantum-espresso/Dockerfile
        context: builds/quantum-espresso/
        username: chrisjsewell
        password: ${{ secrets.DOCKER_HUB }}
        buildargs: QE_GIT_TAG,QE_MAKE
        tags: ${{ matrix.qe_version }}-${{ matrix.qe_make }}
        cache: true
